# Generated by Django 5.0.14 on 2026-03-06 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "type_program",
                    models.CharField(
                        choices=[
                            ("PREGRADO", "Pregrado"),
                            ("POSGRADO", "Posgrado"),
                            ("TECNOLOGO", "Tecnólogo"),
                            ("ESPECIALIZACION", "Especialización"),
                            ("MASTER", "Master"),
                        ],
                        default="PREGRADO",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quotas", models.IntegerField()),
                ("credit_number", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PRESENCIAL", "Presencial"),
                            ("VIRTUAL", "Virtual"),
                            ("HIBRIDO", "Híbrido"),
                        ],
                        default="PRESENCIAL",
                        max_length=10,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="universidad.program",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="universidad.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="universidad.student",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="inscription",
            constraint=models.UniqueConstraint(
                fields=("student", "course"), name="unique_student_course"
            ),
        ),
    ]
