# Generated by Django 5.0.14 on 2026-03-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
