# Generated by Django 5.0.14 on 2026-03-11 18:51

from django.db import migrations


def generate_emails(apps, schema_editor):
    Student = apps.get_model("universidad", "Student")

    for student in Student.objects.all():
        email = student.name.lower().replace(" ", ".") + "@gmail.com"
        student.email = email
        student.save()

class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0002_student_email"),
    ]

    operations = [
        migrations.RunPython(generate_emails),
    ]