# Generated by Django 5.0.14 on 2026-03-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0003_auto_20260311_1851"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
